# This is a basic workflow to help you get started with Actions

name: PDF and OCR layer creator

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 23 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  creating_Pdfs:
    runs-on: ubuntu-latest
    # The type of runner that the job will run on

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ocrmypdf
          version: 1.0
      - name: Installing Write
        run: |
          wget -O Write.tar.gz https://www.styluslabs.com/download/write-tgz --no-check-certificate
          mkdir Write
          tar -zxfv Write.tar.gz -C Write --strip-components 1

      - name: Creating PDFs
        run: |
          sudo chmod u+x PdfScript/pdfcreator.sh
          ./PdfScript/pdfcreator.sh
      
      - name: Creating OCR layer
        run: find . -name *-DavideTonelli.pdf -exec ocrmypdf --language eng --output-type pdf --verbose 1 {} {} \;
